### ISSUE TITLE
problem with translator?

### ISSUE THREAD

**Issue by n-salvi** [noid-group/BOCS#10]
I should start by saying that I am running gromacs 2019.4, so maybe the problem is due to compatibility with newer versions of gromacs?

anyways, when running translator on the .tpr dump file (using either my tpr or one derived from the 1-site methanol example), I get the following error:

ERROR: unable to read expected 1 argument from line
	#atoms_mol
      #posres_xA                     = 0

Any clues?

Many thanks,

Nicola

**Comment by mdelyser** [comment]
Hi Nicola,

Every now and then, GROMACS changes the format of a dumped tpr file, and we have to update our code to account for that. I just installed 2019.4 and two major changes jump out at me that require changes to our code:

1) the error you're seeing is caused because older versions of GROMACS would print moltype, #molecules, #atoms_mol, #posres_xA, #posres_xB for each molblock. It appears the newest version no longer prints #atoms_mol, so we expected to find it but couldn't. So we'll need to get the number of atoms in each molecule type from somewhere else and not error when we don't find #atoms_mol.

2) For each moltype, they used to only print interaction types that were actually present in the molecule. Now, they're explicitly telling you that there are no interactions for every type of interaction that isn't present, which is going to require a decent modification to deal with.

Hopefully, it won't take me too long to get these done.

Thank you for bringing the issue arising from the new gromacs version to our attention.

Regards,

Michael DeLyser

**Comment by n-salvi** [comment]
Thank you Michael for your prompt reply. Sounds good! Would it be worth it installing gromacs 5.1.4 or you think a workaround on your behalf will be available soon enough?

Kind regards,

Nicola

**Comment by mdelyser** [comment]
installing gromacs 5.1.4 would certainly be faster.

I have the fix implemented, but I haven't yet finished checking to make sure that 1) it does what we need it to do and 2) it didn't break something else. Hopefully I will be done testing it sometime tomorrow, at which point I will upload it to github (assuming it does indeed work).

**Comment by mdelyser** [comment]
Nicola,

I just added the fix so we should be able to handle .tpr files dumped with gromacs 2019.4, so I am closing this issue.

Thank you for bringing this issue to our attention. If you run into any other problems, please let us know.

Michael DeLyser
