### ISSUE TITLE
Suggestions for stderr readability 

### ISSUE THREAD

**Issue by sjwoerner** [noid-group/BOCS#7]
Hello there,
I noticed, that the strerr files when running BOCS on the cluster can be quite large. For example, every MPI rank prints “Site type X, Checking X-X...”. Would it suffice to print this only once?

Also, as I understand the output printed to stderr, every MPI rank reads every frame of the trajectory for the first half of the force-matching calculation and prints “Reading frame: n”. This happens regardless of whether or not this MPI rank is using this frame for the calculation or not. My suggestion would be to only print the statement, when the frame is being used for the calculation. This would make it easier to spot, if MPI is working correctly (starting n_rank calculations on one processor each, instead of starting one calculation with n_ranks). And additionally create more manageable stderr files.

**Comment by mdelyser** [comment]
Yes, it would suffice to print that Site type info only once. I'll add a boolean variable to that function so only the first processor prints it out.

As for printing out the frame counter, it is unfortunate that carriage returns don't translate well when stderr gets redirected to a file instead of the screen. The print statement to print the number of the frame is in the function that reads the frame itself, independent of whether or not a specific processor will use that frame or not. Originally that was done simply to mimic GROMACS. It's more useful for a quick program like cgmap that can be run from the command line. 

As a resolution, I made the original print statement optional and turned off for cgff. Additionally, I don't think printing the frame counts whether a given processor uses the frame or not is very helpful. By default, cgff will no longer print anything about frame counts until the very end ("Done after frame XXX"). If you would like to see which processor uses which frame from which file, then at the top of cgff.c, change DEBUG_PRINT_FRAME_COUNT from FALSE to TRUE.
