### ISSUE TITLE
Problem with TPR directives

### ISSUE THREAD

**Issue by sjwoerner** [noid-group/BOCS#9]
Hello,
By fixing issue 2 and changing the definition of KEY_TPR_EXCL from "[TOP_EXCL]" to "[TPR_EXCL]", the code cannot function properly. The code uses the strstr function, which searches for a substring, and checks for KEY_TPR, defined as "TPR" before "TPR_EXCL". Therefore, using TPR_EXCL directive results in the code interpreting this as an additional TPR directive. The check order can be inversed to solve this or the directive renamed.

**Comment by mdelyser** [comment]
Hello,

Sorry about that. When you pointed out the typo in the manual in issue 2, I should have changed the manual to reflect the code, instead of changing the code to reflect the manual. I was lazy because changing the code was easier. My mistake.

Instead of switching the order of the check for the directives, I changed KEY_TPR_EXCL back to TOP_EXCL as it was initially, and also updated the manual accordingly, since I should have done that before.

Thank you for bringing this to our attention.

Michael DeLyser
